<?php

namespace ShopBundle\Repository;

/**
 * CategorieQRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieQRepository extends \Doctrine\ORM\EntityRepository
{
}
