<?php

namespace ShopBundle\Repository;

/**
 * CategorieFRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieFRepository extends \Doctrine\ORM\EntityRepository
{
}
