<?php

namespace ShopBundle\Repository;

/**
 * commande_produitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class commande_produitRepository extends \Doctrine\ORM\EntityRepository
{
}
