<?php

namespace ShopBundle\Repository;

/**
 * commandeFRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class commandeFRepository extends \Doctrine\ORM\EntityRepository
{
}
