<?php

namespace ShopBundle\Repository;

/**
 * commandePRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class commandePRepository extends \Doctrine\ORM\EntityRepository
{
}
