<?php

namespace ShopBundle\Repository;

/**
 * LivrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LivrRepository extends \Doctrine\ORM\EntityRepository
{
    /*public function  editHistoryAdQB(){

        $query=$this->getEntityManager()
            ->createQuery("UPDATE ShopBundle:Livr v SET v.status=:stat")
            ->setParameter(':stat','Envoyé')
            ->execute();

    }

    public function  editCurrentAdQB($idv){

        $query=$this->getEntityManager()
            ->createQuery("UPDATE ShopBundle:Livr v SET v.status=:stat where v.idv='$idv'")
            ->setParameter(':stat','Traité')
            ->execute();

    }*/
}

