<?php

namespace ShopBundle\Repository;

/**
 * panier_produitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class panier_produitRepository extends \Doctrine\ORM\EntityRepository
{
}
