<?php

namespace ShopBundle\Repository;

use Doctrine\ORM\EntityRepository;
use ShopBundle\Entity\Soc;
use Doctrine\ORM\Query;

/**
 * SocRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class SocRepository extends EntityRepository
{
    /*public function findEntitiesByString($str){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p
                FROM ShopBundle:Soc p
                WHERE p.names LIKE :str'
            )
            ->setParameter('str', '%'.$str.'%')
            ->getResult();
    }*/
}