<?php

namespace ShopBundle\Repository;

/**
 * VehRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VehRepository extends \Doctrine\ORM\EntityRepository
{
    public function  editCurrentAdQB(){

        $query=$this->getEntityManager()
            ->createQuery("UPDATE ShopBundle:Veh v SET v.status=:stat WHERE CURRENT_DATE() BETWEEN v.debutcontrat AND v.fincontrat")
            ->setParameter(':stat','1')
            ->execute();

    }
    public function  editHistoryAdQB(){

        $query=$this->getEntityManager()
            ->createQuery("UPDATE ShopBundle:Veh v SET v.status=:stat WHERE CURRENT_DATE() > v.fincontrat")
            ->setParameter(':stat','2')
            ->execute();

    }
    public function  editProgAdQB(){

        $query=$this->getEntityManager()
            ->createQuery("UPDATE ShopBundle:Veh v SET v.status=:stat WHERE CURRENT_DATE() < v.debutcontrat")
            ->setParameter(':stat','0')
            ->execute();
    }



    /*public function ajoutertemps($idad)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'select
                               a.idad,
                               a.fincontrat,
                               DATE_ADD(a.date, INTERVAL 10 DAY) ,
                               DATE_DIFF(date(now()), a.date) ,
                        FROM
                                ShopBundle:Veh a'
            ;
    }*/
}
